# Generated by Django 3.2.2 on 2021-05-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='studentId',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
