# Generated by Django 3.2.2 on 2021-08-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210816_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='check',
            field=models.CharField(default='False', max_length=6),
        ),
    ]
